Repository hanami/assets, pull requests merged in 2019-01, with the labels that each got.

#97 Ruby 2.6
  .circleci/config.yml
  .travis.yml
Labels: enhancement

#98 Disable nested assets by default
  lib/hanami/assets/compiler.rb
  lib/hanami/assets/configuration.rb
  spec/integration/hanami/assets/compiler_spec.rb
  spec/unit/hanami/assets/configuration_spec.rb
Labels: fix

#99 Fix hanamirb.org/guides link to guides.hanamirb.org
  README.md
Labels: fix

#100 Support MRI 2.5+
  .circleci/config.yml
  .travis.yml
  CHANGELOG.md
  README.md
  hanami-assets.gemspec
Labels: breaking-change
